project:
  type: website
  output-dir: docs
  
resources:
  - styles.css
  - files/PSaha-CV.pdf
  - images/PSHeadshot.jpg

website:
  title: "Priyonto Saha"
  search: false

format:
  html:
    theme: Litera
    css: styles.css
    toc: true
    
about:
  template: jolla
  image: images/PSHeadshot.jpg
  links:
    - icon: file-earmark-arrow-down-fill
      text: CV
      href: files/PSaha-CV.pdf
    - icon: envelope-fill
      text: Email
      href: mailto:priyonto.saha@mail.mcgill.ca
    - icon: github
      text: GitHub
      href: https://github.com/P-Saha
    - icon: linkedin
      text: Linkedin
      href: https://www.linkedin.com/in/priyontosaha/
    - icon: google
      text: Google Scholar
      href: https://scholar.google.ca/citations?hl=en&authuser=3&user=z2V834IAAAAJ

editor: visual

execute:
  freeze: auto
  
engine: knitr
